/**
 * Generates a reference document tracking how many times each COLREG rule (whole section)
 * has been asked in the verbatim exam scenarios. Subsection refs (R3g, R7c) count toward
 * their parent rule (R3, R7).
 * Output: content-tools/reports/Rule_Usage_Report.md, content-tools/PDF reference Documents/Rule_Usage_Report.pdf
 * Run: node "content-tools/Question PDF generaters/generateRuleUsageReport.js"
 */
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { examScenarios } = require('../../scripts/verbatimScenarioData.js');
const { colregsRules } = require('../../scripts/colregs-data.js');

/**
 * Normalize a rule ref for counting: detect sub-parts (letter subsections) but strip roman numerals.
 * R10di, R10dii -> R10d (both count toward R10d)
 * R8fiii -> R8f
 * R3i, R3g, R7c -> kept as-is (letter subsections)
 */
function normalizeRefForCounting(ref) {
    let s = String(ref).trim().replace(/^R\.?\s*/i, '').replace(/[\s,]+/g, '').toLowerCase();
    const first = s.split(/[\/&,]/)[0].trim();
    const m = first.match(/^(\d+)([a-l])([ivxlcdm]+)?$/i);
    if (m) {
        const [, num, letter] = m;
        return `R${num}${letter.toLowerCase()}`;
    }
    const whole = first.match(/^(\d+)$/);
    if (whole) return `R${whole[1]}`;
    const letterOnly = first.match(/^(\d+)([a-l])$/i);
    if (letterOnly) return `R${letterOnly[1]}${letterOnly[2]}`;
    const numOnly = first.match(/^(\d+)/);
    return numOnly ? `R${numOnly[1]}` : ref;
}

/**
 * Collect ruleRefs from exam scenarios. Uses sub-parts (R3g, R10d) and strips roman numerals
 * (R10di, R10dii both count toward R10d).
 */
function countRuleRefsFromExams() {
    const counts = {};
    for (const block of examScenarios) {
        for (const q of block.questions || []) {
            const items = (q.subParts && q.subParts.length) ? q.subParts : [q];
            for (const item of items) {
                const ref = item.ruleRef;
                if (ref) {
                    const key = normalizeRefForCounting(ref);
                    counts[key] = (counts[key] || 0) + 1;
                }
            }
        }
    }
    return counts;
}

/** Rules 20-33 and 36-38 are excluded from the usage report. */
function isExcludedRule(ref) {
    if (ref === 'annex4') return false;
    const ruleNum = parseInt(ref.replace(/\D/g, ''), 10);
    if (ruleNum >= 20 && ruleNum <= 33) return true;
    if (ruleNum >= 36 && ruleNum <= 38) return true;
    return false;
}

/**
 * Extract all refs (R1a, R1b, R2, R3a, ...) from colregs for rules 1-19, 34, 35.
 * Each verbatim item starting with (a), (b), etc. becomes R{n}{letter}; intro text becomes R{n}.
 * Base R{n} is always included.
 */
function getAllRefsFromColregs() {
    const refSet = new Set();
    for (const rule of colregsRules) {
        if (isExcludedRule(`R${rule.number}`)) continue;
        refSet.add(`R${rule.number}`);
        const verbatim = rule.verbatim || [];
        for (let i = 0; i < verbatim.length; i++) {
            const m = String(verbatim[i]).trim().match(/^\(([a-z])\)/i);
            if (m) refSet.add(`R${rule.number}${m[1].toLowerCase()}`);
            else if (i === 0) refSet.add(`R${rule.number}`);
        }
    }
    refSet.add('annex4');
    return refSet;
}

/**
 * Build list of sub-part refs for display. Uses complete list from colregs (rules 1-19, 34, 35, Annex IV)
 * so every ref is shown with its count (0 if never asked). Sorted by rule number then letter.
 */
function buildDisplayRefs(counts) {
    const refSet = getAllRefsFromColregs();
    const refs = Array.from(refSet).sort((a, b) => {
        if (a === 'annex4') return 1;
        if (b === 'annex4') return -1;
        const numA = parseInt(a.replace(/\D/g, ''), 10) || 0;
        const numB = parseInt(b.replace(/\D/g, ''), 10) || 0;
        if (numA !== numB) return numA - numB;
        const letterA = (a.match(/[a-z]$/i) || [])[0] || '';
        const letterB = (b.match(/[a-z]$/i) || [])[0] || '';
        return letterA.localeCompare(letterB);
    });
    return refs;
}

function generateReport() {
    const counts = countRuleRefsFromExams();
    const displayRefs = buildDisplayRefs(counts);

    const rows = displayRefs.map(ref => ({
        ref,
        count: counts[ref] ?? 0,
        ruleNum: ref === 'annex4' ? 'annex' : parseInt(ref.replace(/\D/g, ''), 10)
    }));

    const practiceRefs = new Set(rows.map(r => r.ref));
    const totalRefs = practiceRefs.size;
    const totalAsked = rows.reduce((a, r) => a + r.count, 0);
    const neverAsked = rows.filter(r => r.count === 0).length;

    const lines = [
        '# COLREG Rule Usage Report (Practice Mode)',
        '',
        'Rules 1-19, 34, 35 and Annex IV. Times each has been asked in verbatim exam scenarios.',
        '',
        'Generated by `node "content-tools/Question PDF generaters/generateRuleUsageReport.js"`',
        '',
        '---',
        '',
        '| Ref | Times | Ref | Times | Ref | Times |',
        '|-----|-------|-----|-------|-----|-------|',
    ];

    let prevRule = null;
    for (let i = 0; i < rows.length; i += 3) {
        const trio = [rows[i], rows[i + 1], rows[i + 2]];
        const firstRule = rows[i]?.ruleNum;
        if (prevRule !== null && firstRule !== undefined && firstRule !== prevRule) {
            lines.push('|     |       |     |       |     |       |');
        }
        const cells = trio.map(r => r ? [r.ref, r.count] : ['', '']).flat();
        lines.push('| ' + cells.join(' | ') + ' |');
        const last = rows[i + 2] ?? rows[i + 1] ?? rows[i];
        if (last) prevRule = last.ruleNum;
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push(`**Summary:** ${totalRefs} refs total | ${totalAsked} exam question refs | ${neverAsked} never asked (0).`);
    lines.push('');

    const outDir = path.join(__dirname, '..', 'reports');
    const outPath = path.join(outDir, 'Rule_Usage_Report.md');
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
    console.log(`Created: ${outPath}`);

    generatePdf(rows, counts, totalAsked, totalRefs, neverAsked);
}

function generatePdf(rows, counts, totalAsked, totalRefs, neverAsked) {
    const outDir = path.join(__dirname, '..', 'PDF reference Documents');
    const outPath = path.join(outDir, 'Rule_Usage_Report.pdf');
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

    const doc = new PDFDocument({ size: 'A4', layout: 'portrait', margin: 20 });
    const write = fs.createWriteStream(outPath);
    doc.pipe(write);

    const pageWidth = 595;
    const pageHeight = 842;
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;
    const contentHeight = pageHeight - 2 * margin;

    doc.fontSize(20).font('Helvetica-Bold').text('COLREG Rule Usage Report (Practice Mode)', { align: 'center', width: contentWidth });
    doc.moveDown(0.2);
    doc.fontSize(12).font('Helvetica').fillColor('#555555').text('Rules 1-19, 34, 35 and Annex IV. Times each has been asked in verbatim exam scenarios.', { align: 'center', width: contentWidth });
    doc.fillColor('black').moveDown(0.8);

    const cols = 4;
    const cellW = contentWidth / 8;
    const numRows = Math.ceil(rows.length / cols);
    const numSpacers = 17;
    const tableTop = doc.y;
    const tableHeight = contentHeight - (tableTop - margin) - 50;
    const rowH = Math.floor(tableHeight / (numRows + numSpacers * 0.5));
    const spacerH = Math.max(6, Math.floor(rowH * 0.5));

    function drawCell(x, y, w, h, text, bold = false, fill = null, neverAsked = false) {
        if (fill) doc.rect(x, y, w, h).fill(fill);
        doc.rect(x, y, w, h).stroke();
        doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(12);
        const textColor = neverAsked ? '#cc0000' : (fill ? '#333333' : 'black');
        doc.fillColor(textColor).text(String(text), x + 4, y + 4, { width: w - 8, align: 'left' });
        doc.fillColor('black');
    }

    function drawSpacer(y) {
        y += spacerH;
        return y;
    }

    let y = doc.y;

    for (let c = 0; c < cols; c++) {
        drawCell(margin + c * 2 * cellW, y, cellW, rowH, 'Ref', true, '#e8e8e8');
        drawCell(margin + c * 2 * cellW + cellW, y, cellW, rowH, 'Times', true, '#e8e8e8');
    }
    y += rowH;

    let prevRule = null;
    for (let i = 0; i < rows.length; i += cols) {
        const firstRule = rows[i]?.ruleNum;
        if (prevRule !== null && firstRule !== undefined && firstRule !== prevRule) {
            y = drawSpacer(y);
        }
        const fill = Math.floor(i / cols) % 2 === 0 ? '#f9f9f9' : null;
        for (let c = 0; c < cols; c++) {
            const r = rows[i + c];
            const cx = margin + c * 2 * cellW;
            if (r) {
                const neverAsked = r.count === 0;
                drawCell(cx, y, cellW, rowH, r.ref, false, fill, neverAsked);
                drawCell(cx + cellW, y, cellW, rowH, r.count, false, fill, neverAsked);
            } else {
                drawCell(cx, y, cellW, rowH, '', false, fill);
                drawCell(cx + cellW, y, cellW, rowH, '', false, fill);
            }
        }
        y += rowH;
        const last = rows[i + 3] ?? rows[i + 2] ?? rows[i + 1] ?? rows[i];
        if (last) prevRule = last.ruleNum;
    }

    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(12).fillColor('#555555').text(`Summary: ${totalRefs} refs total | ${totalAsked} exam question refs | ${neverAsked} never asked (0)`, { width: contentWidth });
    doc.fillColor('black');

    doc.end();
    write.on('finish', () => console.log(`Created: ${outPath}`));
}

generateReport();
